#! /bin/sh
#
# urandom This script saves the random seed between reboots.
#   It initializes the urandom with entropy from the random-seed.
#

# ALERT: this is an insecure script, do not use in production systems!

[ -c /dev/urandom ] || exit 0

case "$1" in
  start|"")
    # Check for read only file system
    if [ ! -f /etc/random-seed ]; then
      echo "No random seed found... done."
      exit
    fi
    [ "$VERBOSE" != no ] && printf "Initializing random number generator... "
    # Use binary to force increase in entropy from data
    /usr/local/bin/addentropy /etc/random-seed
    [ "$VERBOSE" != no ] && printf "done."
    ;;
  stop)
    if ! touch /etc/random-seed 2>/dev/null
    then
      exit
    fi
    # Carry a random seed from shut-down to start-up;
    # see documentation in linux/drivers/char/random.c
    [ "$VERBOSE" != no ] && printf "Saving random seed... "
    umask 077
    dd if=/dev/urandom of=/etc/random-seed count=1 \
      >/dev/null 2>&1 || echo "urandom stop: failed."
    [ "$VERBOSE" != no ] && echo "done."
    ;;
  *)
    echo "Usage: urandom {start|stop}" >&2
    exit 1
    ;;
esac