#!/bin/sh
#
# nfsroot     mount external root partition (from NFS) and bind
#

umask 077

start() {
    printf "Mounting external root partition..."
    mount EXTERNAL_MOUNT_POINT /mnt
    if [ ! $? -eq 0 ]; then
        echo "failed."
        exit
    fi
    echo "done"
    printf "Binding to external filesystem..."
    cd /mnt
    cp /etc/resolv.conf etc/resolv.conf
    mount -t proc proc proc/
    mount -t sysfs sys sys/
    mount --bind /dev dev/
    mount -t devpts devpts dev/pts/
    mount --bind /dev/shm/ dev/shm/
    mount --bind /run run/
    mount --bind /tmp tmp/
    echo "done"
}
stop() {
    cd /mnt
    umount proc/
    umount sys/
    umount dev/pts
    umount dev/shm
    umount dev/
    umount run/
    umount tmp/
    cd /
    umount /mnt
    echo "OK"
}
restart() {
	  stop
	  start
}

case "$1" in
    start)
	      start
	      ;;
    stop)
	      stop
	      ;;
    restart|reload)
	      restart
	      ;;
    *)
	      echo "Usage: $0 {start|stop|restart}"
	      exit 1
esac

exit $?
