#!/bin/bash

#export HERCULES_ARCH="PULP"
#export HERCULES_FORCE_FOOTPRINT_DENSE=1
#export HERCULES_CPU_MEMORY_SIZE=32768
#export HERCULES_DISQ_THRESHOLD=0
#export HERCULES_DMA_ENFORCE
#export HERCULES_INTERVAL_STATS
#export HERCULES_DEFAULT_NUM_THREADS=8
#export HERCULES_NO_INTERVAL_CONTROLFLOW
#export HERCULES_DUMP_REGIONS_PATH=~/Downloads/regions-%a.xml
#export HERCULES_DUMP_INTERVALS_PATH=~/Downloads/intervals-%a.xml
#export HERCULES_WHITELIST="gemm_nn gemm_cpu gemm .omp_outlined.
#__omp_offloading_803_1108d5d_gemm_zero_l125 __omp_offloading_803_1108d69_gemm_zero_l125
#__omp_offloading_803_1108bea_gemm_zero_l126 __omp_offloading_803_1108d79_gemm_zero_l125
#__omp_offloading_803_1108d67_gemm_zero_l125 __omp_offloading_803_1108d0b_gemm_zero_l125
#__omp_offloading_803_1108d58_gemm_zero_l125 __omp_offloading_803_1108d62_gemm_zero_l125
#__omp_offloading_803_1108d57_gemm_zero_l126 __omp_offloading_803_1108d6c_gemm_zero_l125
#__omp_offloading_803_1108d7b_gemm_zero_l125 __omp_offloading_803_1108d52_gemm_zero_l125"
#source ${HERCULES_INSTALL}/../toolchain/HerculesCompiler-public/environment.sh

source ${HERO_INSTALL}/../env/exilzcu102.sh
make default-as=pulp clean all
scp memory_copy root@hero-zcu102-06:${HERO_TARGET_PATH_APPS}
