-include $GIT_TOP/hardware/deps/axi/include
-include $GIT_TOP/hardware/deps/axi/include/axi
-include $GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco
-include $GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco
-include $GIT_TOP/hardware/deps/cluster_peripherals/event_unit/include
-include $GIT_TOP/hardware/deps/common_cells/include
-include $GIT_TOP/hardware/deps/event_unit_flex
-include $GIT_TOP/hardware/deps/riscv/rtl/include
-include $GIT_TOP/hardware/src/apb/include
-include $GIT_TOP/hardware/deps/axi/include
-include $GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco
-include $GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco
-include $GIT_TOP/hardware/deps/cluster_peripherals/event_unit/include
-include $GIT_TOP/hardware/deps/common_cells/include
-include $GIT_TOP/hardware/deps/event_unit_flex
-include $GIT_TOP/hardware/deps/riscv/rtl/include
-include $GIT_TOP/hardware/src/apb/include
$GIT_TOP/hardware/deps/tech_cells_generic/src/deprecated/cluster_clk_cells_xilinx.sv
$GIT_TOP/hardware/deps/tech_cells_generic/src/fpga/tc_clk_xilinx.sv
$GIT_TOP/hardware/deps/tech_cells_generic/src/fpga/tc_sram_xilinx.sv
$GIT_TOP/hardware/deps/tech_cells_generic/src/deprecated/pulp_clock_gating_async.sv
$GIT_TOP/hardware/deps/common_cells/src/cdc_2phase.sv
$GIT_TOP/hardware/deps/common_cells/src/cf_math_pkg.sv
$GIT_TOP/hardware/deps/common_cells/src/clk_div.sv
$GIT_TOP/hardware/deps/common_cells/src/delta_counter.sv
$GIT_TOP/hardware/deps/common_cells/src/ecc_pkg.sv
$GIT_TOP/hardware/deps/common_cells/src/edge_propagator_tx.sv
$GIT_TOP/hardware/deps/common_cells/src/exp_backoff.sv
$GIT_TOP/hardware/deps/common_cells/src/fifo_v3.sv
$GIT_TOP/hardware/deps/common_cells/src/graycode.sv
$GIT_TOP/hardware/deps/common_cells/src/isochronous_spill_register.sv
$GIT_TOP/hardware/deps/common_cells/src/lfsr.sv
$GIT_TOP/hardware/deps/common_cells/src/lfsr_16bit.sv
$GIT_TOP/hardware/deps/common_cells/src/lfsr_8bit.sv
$GIT_TOP/hardware/deps/common_cells/src/mv_filter.sv
$GIT_TOP/hardware/deps/common_cells/src/onehot_to_bin.sv
$GIT_TOP/hardware/deps/common_cells/src/plru_tree.sv
$GIT_TOP/hardware/deps/common_cells/src/popcount.sv
$GIT_TOP/hardware/deps/common_cells/src/rr_arb_tree.sv
$GIT_TOP/hardware/deps/common_cells/src/rstgen_bypass.sv
$GIT_TOP/hardware/deps/common_cells/src/serial_deglitch.sv
$GIT_TOP/hardware/deps/common_cells/src/shift_reg.sv
$GIT_TOP/hardware/deps/common_cells/src/spill_register.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_demux.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_filter.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_fork.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_intf.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_join.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_mux.sv
$GIT_TOP/hardware/deps/common_cells/src/sub_per_hash.sv
$GIT_TOP/hardware/deps/common_cells/src/sync.sv
$GIT_TOP/hardware/deps/common_cells/src/sync_wedge.sv
$GIT_TOP/hardware/deps/common_cells/src/unread.sv
$GIT_TOP/hardware/deps/common_cells/src/rr_distributor.sv
$GIT_TOP/hardware/deps/common_cells/src/addr_decode.sv
$GIT_TOP/hardware/deps/common_cells/src/cb_filter.sv
$GIT_TOP/hardware/deps/common_cells/src/cdc_fifo_2phase.sv
$GIT_TOP/hardware/deps/common_cells/src/cdc_fifo_gray.sv
$GIT_TOP/hardware/deps/common_cells/src/counter.sv
$GIT_TOP/hardware/deps/common_cells/src/ecc_decode.sv
$GIT_TOP/hardware/deps/common_cells/src/ecc_encode.sv
$GIT_TOP/hardware/deps/common_cells/src/edge_detect.sv
$GIT_TOP/hardware/deps/common_cells/src/lzc.sv
$GIT_TOP/hardware/deps/common_cells/src/max_counter.sv
$GIT_TOP/hardware/deps/common_cells/src/rstgen.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_delay.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_fifo.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_fork_dynamic.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_xbar.sv
$GIT_TOP/hardware/deps/common_cells/src/fall_through_register.sv
$GIT_TOP/hardware/deps/common_cells/src/id_queue.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_to_mem.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_arbiter_flushable.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_register.sv
$GIT_TOP/hardware/deps/common_cells/src/stream_arbiter.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/clock_divider_counter.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/find_first_one.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/generic_LFSR_8bit.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/generic_fifo.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/prioarbiter.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/pulp_sync.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/pulp_sync_wedge.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/rrarbiter.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/clock_divider.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/fifo_v2.sv
$GIT_TOP/hardware/deps/common_cells/src/deprecated/fifo_v1.sv
$GIT_TOP/hardware/deps/common_cells/src/edge_propagator.sv
$GIT_TOP/hardware/deps/common_cells/src/edge_propagator_rx.sv
$GIT_TOP/hardware/deps/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
$GIT_TOP/hardware/deps/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
$GIT_TOP/hardware/deps/fpu_div_sqrt_mvp/hdl/control_mvp.sv
$GIT_TOP/hardware/deps/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
$GIT_TOP/hardware/deps/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
$GIT_TOP/hardware/deps/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
$GIT_TOP/hardware/deps/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
$GIT_TOP/hardware/deps/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/interfaces/tcdm_bank_mem_bus.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/interfaces/xbar_periph_bus.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/interfaces/xbar_tcdm_bus_64.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/interfaces/xbar_tcdm_bus.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/AddressDecoder_Req.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/AddressDecoder_Resp.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/FanInPrimitive_Req.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/FanInPrimitive_Resp.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/MUX2_REQ.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/TCDM_PIPE_REQ.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/TCDM_PIPE_RESP.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/TestAndSet.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/grant_mask.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/priority_Flag_Req.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/ArbitrationTree.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/ResponseTree.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/RequestBlock1CH.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/RequestBlock2CH.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/ResponseBlock.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/XBAR_TCDM.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/low_latency_interco/XBAR_TCDM_WRAPPER.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/AddressDecoder_PE_Req.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/AddressDecoder_Resp_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/FanInPrimitive_PE_Resp.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/FanInPrimitive_Req_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/MUX2_REQ_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/RR_Flag_Req_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/ArbitrationTree_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/ResponseTree_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/ResponseBlock_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/RequestBlock1CH_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/RequestBlock2CH_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/peripheral_interco/XBAR_PE.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/tcdm_interconnect/tcdm_interconnect_pkg.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/tcdm_interconnect/addr_dec_resp_mux.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/tcdm_interconnect/amo_shim.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/tcdm_interconnect/xbar.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/tcdm_interconnect/clos_net.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/tcdm_interconnect/bfly_net.sv
$GIT_TOP/hardware/deps/cluster_interconnect/rtl/tcdm_interconnect/tcdm_interconnect.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_pkg.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_cast_multi.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_classifier.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_divsqrt_multi.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_fma.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_fma_multi.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_noncomp.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_opgroup_block.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_opgroup_fmt_slice.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_opgroup_multifmt_slice.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_rounding.sv
$GIT_TOP/hardware/deps/fpnew/src/fpnew_top.sv
$GIT_TOP/hardware/deps/axi/src/axi_pkg.sv
$GIT_TOP/hardware/deps/axi/src/dma/axi_dma_data_path.sv
$GIT_TOP/hardware/deps/axi/src/axi_intf.sv
$GIT_TOP/hardware/deps/axi/src/dma/axi_dma_data_mover.sv
$GIT_TOP/hardware/deps/axi/src/dma/axi_dma_burst_reshaper.sv
$GIT_TOP/hardware/deps/axi/src/axi_atop_filter.sv
$GIT_TOP/hardware/deps/axi/src/axi_burst_splitter.sv
$GIT_TOP/hardware/deps/axi/src/axi_cdc.sv
$GIT_TOP/hardware/deps/axi/src/axi_cut.sv
$GIT_TOP/hardware/deps/axi/src/axi_delayer.sv
$GIT_TOP/hardware/deps/axi/src/axi_demux.sv
$GIT_TOP/hardware/deps/axi/src/axi_dw_downsizer.sv
$GIT_TOP/hardware/deps/axi/src/axi_dw_upsizer.sv
$GIT_TOP/hardware/deps/axi/src/axi_id_remap.sv
$GIT_TOP/hardware/deps/axi/src/axi_id_prepend.sv
$GIT_TOP/hardware/deps/axi/src/axi_isolate.sv
$GIT_TOP/hardware/deps/axi/src/axi_join.sv
$GIT_TOP/hardware/deps/axi/src/axi_lite_demux.sv
$GIT_TOP/hardware/deps/axi/src/axi_lite_join.sv
$GIT_TOP/hardware/deps/axi/src/axi_lite_mailbox.sv
$GIT_TOP/hardware/deps/axi/src/axi_lite_mux.sv
$GIT_TOP/hardware/deps/axi/src/axi_lite_regs.sv
$GIT_TOP/hardware/deps/axi/src/axi_lite_to_apb.sv
$GIT_TOP/hardware/deps/axi/src/axi_lite_to_axi.sv
$GIT_TOP/hardware/deps/axi/src/axi_modify_address.sv
$GIT_TOP/hardware/deps/axi/src/axi_mux.sv
$GIT_TOP/hardware/deps/axi/src/axi_read_burst_buffer.sv
$GIT_TOP/hardware/deps/axi/src/axi_serializer.sv
$GIT_TOP/hardware/deps/axi/src/dma/axi_dma_backend.sv
$GIT_TOP/hardware/deps/axi/src/axi_err_slv.sv
$GIT_TOP/hardware/deps/axi/src/axi_dw_converter.sv
$GIT_TOP/hardware/deps/axi/src/axi_id_serialize.sv
$GIT_TOP/hardware/deps/axi/src/axi_multicut.sv
$GIT_TOP/hardware/deps/axi/src/axi_tlb_l1.sv
$GIT_TOP/hardware/deps/axi/src/axi_to_axi_lite.sv
$GIT_TOP/hardware/deps/axi/src/axi_iw_converter.sv
$GIT_TOP/hardware/deps/axi/src/axi_lite_xbar.sv
$GIT_TOP/hardware/deps/axi/src/axi_tlb.sv
$GIT_TOP/hardware/deps/axi/src/axi_xbar.sv
$GIT_TOP/hardware/deps/axi_slice/src/axi_single_slice.sv
$GIT_TOP/hardware/deps/axi_slice/src/axi_ar_buffer.sv
$GIT_TOP/hardware/deps/axi_slice/src/axi_aw_buffer.sv
$GIT_TOP/hardware/deps/axi_slice/src/axi_b_buffer.sv
$GIT_TOP/hardware/deps/axi_slice/src/axi_r_buffer.sv
$GIT_TOP/hardware/deps/axi_slice/src/axi_slice.sv
$GIT_TOP/hardware/deps/axi_slice/src/axi_w_buffer.sv
$GIT_TOP/hardware/deps/axi_slice/src/axi_slice_wrap.sv
$GIT_TOP/hardware/deps/cluster_peripherals/cluster_control_unit/cluster_control_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/HW_barrier_logic.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/event_unit_arbiter.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/event_unit_mux.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/event_unit_sm.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/interrupt_mask.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/interfaces/bbmux_config_bus.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/interfaces/clkgate_config_bus.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/HW_barrier.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/event_unit_input.sv
$GIT_TOP/hardware/deps/cluster_peripherals/event_unit/event_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/interfaces/l0_ctrl_unit_bus.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/interfaces/mp_icache_ctrl_unit_bus.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/interfaces/mp_pf_icache_ctrl_unit_bus.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/interfaces/pri_icache_ctrl_unit_bus.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/interfaces/sp_icache_ctrl_unit_bus.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/icache_ctrl_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/mp_icache_ctrl_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/mp_pf_icache_ctrl_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/new_icache_ctrl_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/pri_icache_ctrl_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/icache_ctrl_unit/sp_icache_ctrl_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/mmu_config_unit/interfaces/mmu_config_bus.sv
$GIT_TOP/hardware/deps/cluster_peripherals/mmu_config_unit/mmu_config_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/perf_counters_unit/perf_counters_unit.sv
$GIT_TOP/hardware/deps/cluster_peripherals/tcdm_pipe_unit/tcdm_pipe_unit.sv
$GIT_TOP/hardware/deps/icache-intc/Req_Arb_Node_icache_intc.sv
$GIT_TOP/hardware/deps/icache-intc/Resp_Arb_Node_icache_intc.sv
$GIT_TOP/hardware/deps/icache-intc/lint_mux.sv
$GIT_TOP/hardware/deps/icache-intc/DistributedArbitrationNetwork_Req_icache_intc.sv
$GIT_TOP/hardware/deps/icache-intc/DistributedArbitrationNetwork_Resp_icache_intc.sv
$GIT_TOP/hardware/deps/icache-intc/RoutingBlock_Req_icache_intc.sv
$GIT_TOP/hardware/deps/icache-intc/RoutingBlock_2ch_Req_icache_intc.sv
$GIT_TOP/hardware/deps/icache-intc/RoutingBlock_Resp_icache_intc.sv
$GIT_TOP/hardware/deps/icache-intc/icache_intc.sv
$GIT_TOP/hardware/deps/riscv/rtl/include/apu_core_package.sv
$GIT_TOP/hardware/deps/riscv/rtl/include/riscv_defines.sv
$GIT_TOP/hardware/deps/riscv/rtl/include/riscv_tracer_defines.sv
$GIT_TOP/hardware/deps/riscv/rtl/register_file_test_wrap.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_alu.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_alu_basic.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_alu_div.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_compressed_decoder.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_controller.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_cs_registers.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_decoder.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_int_controller.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_ex_stage.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_hwloop_controller.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_hwloop_regs.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_id_stage.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_if_stage.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_load_store_unit.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_mult.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_pmp.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_prefetch_buffer.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_prefetch_L0_buffer.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_core.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_apu_disp.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_fetch_fifo.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_L0_buffer.sv
$GIT_TOP/hardware/deps/riscv/rtl/riscv_register_file.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_1r_1w_all.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_1r_1w_be.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_1r_1w.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_1r_1w_1row.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_1r_1w_raw.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_1w_multi_port_read.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_1w_64b_multi_port_read_32b.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_1w_64b_1r_32b.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_2r_1w_asymm.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_2r_1w_asymm_test_wrap.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_2r_2w.sv
$GIT_TOP/hardware/deps/scm/fpga_scm/register_file_3r_2w.sv
$GIT_TOP/hardware/deps/apb/src/apb_intf.sv
$GIT_TOP/hardware/deps/axi2mem/axi2mem.sv
$GIT_TOP/hardware/deps/axi2per/axi2per_req_channel.sv
$GIT_TOP/hardware/deps/axi2per/axi2per_res_channel.sv
$GIT_TOP/hardware/deps/axi2per/axi2per.sv
$GIT_TOP/hardware/deps/axi_slice_dc/src/axi_slice_dc_master.sv
$GIT_TOP/hardware/deps/axi_slice_dc/src/axi_slice_dc_slave.sv
$GIT_TOP/hardware/deps/axi_slice_dc/src/dc_data_buffer.sv
$GIT_TOP/hardware/deps/axi_slice_dc/src/dc_full_detector.v
$GIT_TOP/hardware/deps/axi_slice_dc/src/dc_synchronizer.v
$GIT_TOP/hardware/deps/axi_slice_dc/src/dc_token_ring_fifo_din.v
$GIT_TOP/hardware/deps/axi_slice_dc/src/dc_token_ring_fifo_dout.v
$GIT_TOP/hardware/deps/axi_slice_dc/src/dc_token_ring.v
$GIT_TOP/hardware/deps/axi_slice_dc/src/axi_slice_dc_master_wrap.sv
$GIT_TOP/hardware/deps/axi_slice_dc/src/axi_slice_dc_slave_wrap.sv
$GIT_TOP/hardware/deps/axi_slice_dc/src/axi_cdc.sv
$GIT_TOP/hardware/deps/event_unit_flex/message_bus.sv
$GIT_TOP/hardware/deps/event_unit_flex/event_unit_core.sv
$GIT_TOP/hardware/deps/event_unit_flex/event_unit_interface_mux.sv
$GIT_TOP/hardware/deps/event_unit_flex/event_unit_top.sv
$GIT_TOP/hardware/deps/event_unit_flex/soc_periph_fifo.sv
$GIT_TOP/hardware/deps/event_unit_flex/interc_sw_evt_trig.sv
$GIT_TOP/hardware/deps/event_unit_flex/hw_barrier_unit.sv
$GIT_TOP/hardware/deps/event_unit_flex/hw_mutex_unit.sv
$GIT_TOP/hardware/deps/event_unit_flex/hw_dispatch.sv
$GIT_TOP/hardware/deps/icache_mp_128_pf/RTL/icache_bank_mp_128.sv
$GIT_TOP/hardware/deps/icache_mp_128_pf/RTL/icache_bank_mp_PF.sv
$GIT_TOP/hardware/deps/icache_mp_128_pf/RTL/merge_refill_cam_128_16.sv
$GIT_TOP/hardware/deps/icache_mp_128_pf/RTL/pf_miss_mux.sv
$GIT_TOP/hardware/deps/icache_mp_128_pf/RTL/prefetcher_if.sv
$GIT_TOP/hardware/deps/icache_mp_128_pf/RTL/central_controller_128.sv
$GIT_TOP/hardware/deps/icache_mp_128_pf/RTL/cache_controller_to_axi_128_PF.sv
$GIT_TOP/hardware/deps/icache_mp_128_pf/RTL/icache_top_mp_128_PF.sv
$GIT_TOP/hardware/deps/per2axi/src/per2axi_busy_unit.sv
$GIT_TOP/hardware/deps/per2axi/src/per2axi_req_channel.sv
$GIT_TOP/hardware/deps/per2axi/src/per2axi_res_channel.sv
$GIT_TOP/hardware/deps/per2axi/src/per2axi.sv
$GIT_TOP/hardware/deps/timer_unit/rtl/timer_unit_counter.sv
$GIT_TOP/hardware/deps/timer_unit/rtl/timer_unit_counter_presc.sv
$GIT_TOP/hardware/deps/timer_unit/rtl/apb_timer_unit.sv
$GIT_TOP/hardware/deps/timer_unit/rtl/timer_unit.sv
$GIT_TOP/hardware/deps/axi2apb/src/axi2apb.sv
$GIT_TOP/hardware/deps/axi2apb/src/axi2apb_64_32.sv
$GIT_TOP/hardware/deps/axi2apb/src/axi2apb_wrap.sv
$GIT_TOP/hardware/deps/axi_riscv_atomics/src/axi_res_tbl.sv
$GIT_TOP/hardware/deps/axi_riscv_atomics/src/axi_riscv_amos_alu.sv
$GIT_TOP/hardware/deps/axi_riscv_atomics/src/axi_riscv_amos.sv
$GIT_TOP/hardware/deps/axi_riscv_atomics/src/axi_riscv_lrsc.sv
$GIT_TOP/hardware/deps/axi_riscv_atomics/src/axi_riscv_atomics.sv
$GIT_TOP/hardware/deps/axi_riscv_atomics/src/axi_riscv_lrsc_wrap.sv
$GIT_TOP/hardware/deps/axi_riscv_atomics/src/axi_riscv_amos_wrap.sv
$GIT_TOP/hardware/deps/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/packages/apu_package.sv
$GIT_TOP/hardware/deps/pulp_cluster/packages/pulp_cluster_package.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/axi2per_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/axi_slice_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cluster_bus_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cluster_clock_gate.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cluster_event_map.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cluster_interconnect_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cluster_timer_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cpu_marx_if.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/dmac_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/per2axi_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/per_demux_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/periph_FIFO.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/periph_demux.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/tryx_ctrl.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/xne_wrap.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cluster_dma_transfer_id_gen.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cluster_dma_frontend_regs.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cluster_peripherals.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/core_demux.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/cluster_dma_frontend.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/xbar_demux_bus.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/core_region.sv
$GIT_TOP/hardware/deps/pulp_cluster/rtl/pulp_cluster.sv
$GIT_TOP/hardware/src/apb/apb_bus.sv
$GIT_TOP/hardware/src/apb/apb_ro_regs.sv
$GIT_TOP/hardware/src/apb/apb_rw_regs.sv
$GIT_TOP/hardware/src/apb/apb_bus_wrap.sv
$GIT_TOP/hardware/src/hero_axi_mailbox.sv
$GIT_TOP/hardware/src/pulp_cluster_cfg_pkg.sv
$GIT_TOP/hardware/src/soc_bus.sv
$GIT_TOP/hardware/src/soc_ctrl_regs.sv
$GIT_TOP/hardware/src/dmac_wrap_ooc.sv
$GIT_TOP/hardware/src/l2_mem.sv
$GIT_TOP/hardware/src/pulp_cluster_ooc.sv
$GIT_TOP/hardware/src/soc_peripherals.sv
$GIT_TOP/hardware/src/pulp.sv
$GIT_TOP/hardware/src/pulp_ooc.sv
