
#ifndef _SNITCH_REG_H
#define _SNITCH_REG_H

/**
 * @brief SoC-control register map
 *
 */
#define SCTL_INTR_STATE_REG_OFFSET 0x0
#define SCTL_INTR_ENABLE_REG_OFFSET 0x4
#define SCTL_INTR_TEST_REG_OFFSET 0x8
#define SCTL_VERSION_REG_OFFSET 0xc
#define SCTL_CHIP_ID_REG_OFFSET 0x10
#define SCTL_SCRATCH_0_REG_OFFSET 0x14
#define SCTL_SCRATCH_1_REG_OFFSET 0x18
#define SCTL_SCRATCH_2_REG_OFFSET 0x1c
#define SCTL_SCRATCH_3_REG_OFFSET 0x20
#define SCTL_BOOT_MODE_REG_OFFSET 0x24
#define SCTL_NUM_QUADRANTS_REG_OFFSET 0x28
#define SCTL_PAD_0_REG_OFFSET 0x2c
#define SCTL_PAD_1_REG_OFFSET 0x30
#define SCTL_PAD_2_REG_OFFSET 0x34
#define SCTL_PAD_3_REG_OFFSET 0x38
#define SCTL_PAD_4_REG_OFFSET 0x3c
#define SCTL_PAD_5_REG_OFFSET 0x40
#define SCTL_PAD_6_REG_OFFSET 0x44
#define SCTL_PAD_7_REG_OFFSET 0x48
#define SCTL_PAD_8_REG_OFFSET 0x4c
#define SCTL_PAD_9_REG_OFFSET 0x50
#define SCTL_PAD_10_REG_OFFSET 0x54
#define SCTL_PAD_11_REG_OFFSET 0x58
#define SCTL_PAD_12_REG_OFFSET 0x5c
#define SCTL_PAD_13_REG_OFFSET 0x60
#define SCTL_PAD_14_REG_OFFSET 0x64
#define SCTL_PAD_15_REG_OFFSET 0x68
#define SCTL_PAD_16_REG_OFFSET 0x6c
#define SCTL_PAD_17_REG_OFFSET 0x70
#define SCTL_PAD_18_REG_OFFSET 0x74
#define SCTL_PAD_19_REG_OFFSET 0x78
#define SCTL_PAD_20_REG_OFFSET 0x7c
#define SCTL_PAD_21_REG_OFFSET 0x80
#define SCTL_PAD_22_REG_OFFSET 0x84
#define SCTL_PAD_23_REG_OFFSET 0x88
#define SCTL_PAD_24_REG_OFFSET 0x8c
#define SCTL_PAD_25_REG_OFFSET 0x90
#define SCTL_PAD_26_REG_OFFSET 0x94
#define SCTL_PAD_27_REG_OFFSET 0x98
#define SCTL_PAD_28_REG_OFFSET 0x9c
#define SCTL_PAD_29_REG_OFFSET 0xa0
#define SCTL_PAD_30_REG_OFFSET 0xa4

/**
 * @brief Quadrant-control register map
 *
 */
#define QCTL_CLK_ENA_REG_OFFSET 0x0
#define QCTL_RESET_N_REG_OFFSET 0x4
#define QCTL_ISOLATE_REG_OFFSET 0x8
#define QCTL_ISOLATED_REG_OFFSET 0xc
#define QCTL_RO_CACHE_ENABLE_REG_OFFSET 0x10
#define QCTL_RO_CACHE_FLUSH_REG_OFFSET 0x14
#define QCTL_RO_START_ADDR_LOW_0_REG_OFFSET 0x100
#define QCTL_RO_START_ADDR_HIGH_0_REG_OFFSET 0x104
#define QCTL_RO_END_ADDR_LOW_0_REG_OFFSET 0x108
#define QCTL_RO_END_ADDR_HIGH_0_REG_OFFSET 0x10c
#define QCTL_RO_START_ADDR_LOW_1_REG_OFFSET 0x110
#define QCTL_RO_START_ADDR_HIGH_1_REG_OFFSET 0x114
#define QCTL_RO_END_ADDR_LOW_1_REG_OFFSET 0x118
#define QCTL_RO_END_ADDR_HIGH_1_REG_OFFSET 0x11c
#define QCTL_RO_START_ADDR_LOW_2_REG_OFFSET 0x120
#define QCTL_RO_START_ADDR_HIGH_2_REG_OFFSET 0x124
#define QCTL_RO_END_ADDR_LOW_2_REG_OFFSET 0x128
#define QCTL_RO_END_ADDR_HIGH_2_REG_OFFSET 0x12c
#define QCTL_RO_START_ADDR_LOW_3_REG_OFFSET 0x130
#define QCTL_RO_START_ADDR_HIGH_3_REG_OFFSET 0x134
#define QCTL_RO_END_ADDR_LOW_3_REG_OFFSET 0x138
#define QCTL_RO_END_ADDR_HIGH_3_REG_OFFSET 0x13c
#define QCTL_TLB_NARROW_REG_OFFSET 0x08000UL
#define QCTL_TLB_WIDE_REG_OFFSET 0x0c000UL

#define QCTL_CLK_ENA_CLK_ENA_BIT 0
#define QCTL_RESET_N_RESET_N_BIT 0
#define QCTL_ISOLATE_NARROW_IN_BIT 0
#define QCTL_ISOLATE_NARROW_OUT_BIT 1
#define QCTL_ISOLATE_WIDE_IN_BIT 2
#define QCTL_ISOLATE_WIDE_OUT_BIT 3
#define QCTL_ISOLATED_NARROW_IN_BIT 0
#define QCTL_ISOLATED_NARROW_OUT_BIT 1
#define QCTL_ISOLATED_WIDE_IN_BIT 2
#define QCTL_ISOLATED_WIDE_OUT_BIT 3
#define QCTL_RO_CACHE_ENABLE_ENABLE_BIT 0
#define QCTL_RO_CACHE_FLUSH_FLUSH_BIT 0

#endif
