#!/bin/bash
set -o errexit

export HERCULES_INSTALL=${HERO_INSTALL}
export HERCULES_ARCH="PULP"
export HERCULES_FORCE_FOOTPRINT_DENSE=1
export HERCULES_CPU_MEMORY_SIZE=32768
#export HERCULES_GPU_MEMORY_SIZE=10000 # CAVEAT still used to manipulate PULP SPM
export HERCULES_DISQ_THRESHOLD=0
export HERCULES_DEFAULT_NUM_THREADS=8
export HERCULES_DMA_ENFORCE
export HERCULES_NO_INTERVAL_CONTROLFLOW
source ${HERCULES_INSTALL}/../toolchain/HerculesCompiler-public/environment.sh

source ${HERO_INSTALL}/../env/exilzcu102.sh

make default-as=pulp clean all
scp helloworld root@hero-zcu102-06:${HERO_TARGET_PATH_APPS}
