puts "${Blue}                                                                        "
puts "${Blue}                     __..----._                                         "
puts "${Blue}                  .--'          `-.                                     "
puts "${Blue}                .'                 `/\                                   "
puts "${Blue}               /          /\--.._____/                                   "
puts "${Blue}             _/          .' ___    _|                                   "
puts "${Blue}           ./  //\  _ _.-'     _`  (_/\                                   "
puts "${Blue}          /    /\ /\/. /\       (_)  /\  /\                                  "
puts "${Blue}         |      /\ /\:;             _)_/-.__._                            "
puts "${Blue}        |       |  /\--'            | | | | ./\                           "
puts "${Blue}        |       |   |  /\         .=-/\| | |/ |                           "
puts "${Blue}        |       |   | -.`-.      /\/\   /\|/\|  |                           "
puts "${Blue}        /\       |  /     `-`-___.--`._      |                           "
puts "${Blue}         /\      | /                   `/\    |                           "
puts "${Blue}          |     //                      /\   |                           "
puts "${Blue}          /\    //                       |    /\                          "
puts "${Blue}           /\   /                        |/\    /\                         "
puts "${Blue}            /\ /                         | /\    /\                        "
puts "${Blue}             `/\                         | |     /\                       "
puts "${Blue}              |                /\        |/\|                             "
puts "${Blue}              /\                |        | /\      /\                      "
puts "${Blue}               |               |        |  )      /\                     "
puts "${Blue}               /\               |        | /       |                     "
puts "${Blue}                /\              |        |/-._____/                      "
puts "${Blue}                 |  /\          |        |                               "
puts "${Blue}                 /\             /\        |                               "
puts "${Blue}                  /\   /\         |       |                               "
puts "${Blue}                   /\            /\        /\                              "
puts "${Blue}                    /\  |         |       |                              "
puts "${Blue}                    |            |        /\                             "
puts "${Blue}                  .'   |         |         /\                            "
puts "${Blue}                 /                /\        |                            "
puts "${Blue}               .'/\    /            /\       `                            "
puts "${Blue}             .'   /\  /             `        /\        _______            "
puts "${Blue}            /      `.               /\       `   .---'       `/\          "
puts "${Blue}           /         `--.___        _/\       /\-'              /\         "
puts "${Blue}         .|                 `------'  /\      `                 /\        "
puts "${Blue}        | |      Mr                    /\      /\          .---  |        "
puts "${Blue}       /  /\       W                     /\     `        .'     /         "
puts "${Blue}     .' `- /\        o                  .-/\     /\    .-'     .'          "
puts "${Blue}    /      //\         l               /   /\     /\.-'      .'            "
puts "${Blue}  _/      / `/\          f             /     /\     /\      .'              "
puts "${Blue} /. `  ' `    /\                    /'       /\     /\   .'                "
puts "${Blue} U',-.-. /     `-                 /   .--.-' /\     ``/\..--.__           "
puts "${Blue}  'UU(__)        `-.__         _.'   /        /\        `/\) )_)          "
puts "${Blue}                      `-------'-.___| _-'    .-`-.   /\ /\/-'             "
puts "${Blue}                                  _-'     .-'    `/\_/\_/\'                "
puts "${Blue}                             _.--'      .'                              "
puts "${Blue}                            ( `  ,.. .-'                                "
puts "${Blue}                             `'-Uuu-'                                   "
puts "${NC}"