#!/bin/bash
set -o errexit

export HERO_INSTALL=/scratch/mmaxim/hero/install
source ${HERO_INSTALL}/../env/exilzcu102.sh
export HERO_TARGET_HOST=root@hero-zcu102-06
export HERO_TARGET_PATH_APPS=/home/root/mmaxim
make default-as=pulp clean all
scp dma-perf ${HERO_TARGET_HOST}:${HERO_TARGET_PATH_APPS}

