#! /bin/bash
# This script crosscompiles benchmarks and sends them to the Zynq board
if [ -z "${HERO_INSTALL}" ]
then
	echo 'Please export the HERO_INSTALL environment variable'
	exit 1
fi


if [ $# -ne 1 ]
then
	echo 'Please provide the memory size'
	exit 1
fi

bindir="./bin"
srcdir="./src"
remotehost=$(sed -n '1 p' config)
remotedir=$(sed -n '2 p' config)
#mem_size=$(sed -n '3 p' config)
mem_size=$1
programs=($(sed -n '4 p' config))
common="-Isrc src/polybench.c"
#poly="${common} -DPOLYBENCH_TIME"
poly="${common}"
suffix=".elf"


# For some esoteric reason, I had to create symlinks to use HERO's clang-9, else the loader would complain:
ln -s ${HERO_INSTALL}/lib/gcc/arm-none-linux-gnueabi/8.3.0/crtbegin.o ./crtbegin.o
ln -s ${HERO_INSTALL}/lib/gcc/arm-none-linux-gnueabi/8.3.0/crtend.o ./crtend.o

#compiler="/scratch/hero/install/bin/clang-9 -O3 -static -L/scratch/hero/install/lib/gcc/arm-none-linux-gnueabi/8.3.0 -mfloat-abi=soft -march=armv7"; source /scratch/hero/env/hero-z-7045-env.sh
compiler="/scratch/hero/install/bin/clang-9 --sysroot=/scratch/hero/install/aarch64-buildroot-linux-gnu/sysroot -target aarch64-hero-linux-gnu -O3"; source /scratch/hero/env/exilzcu102.sh

mkdir -p ${bindir}

for program in ${programs[*]}
do
	prog_size=$(scripts/computesize ${program} ${mem_size})
	size_flags="-DNI=${prog_size} -DNJ=${prog_size} -DNK=${prog_size} -DNL=${prog_size} -DNM=${prog_size} -DN=${prog_size} -DNX=${prog_size} -DNY=${prog_size}" 
	${compiler} ${poly} ${size_flags} -DTIMEKERN ${srcdir}/${program}.c -o ${bindir}/${program}${suffix}
	if [ $? -ne 0 ]
	then
		echo "ERROR: Could not compile ${program}"
		rm crtbegin.o crtend.o
		exit 1
	fi
	scp ${bindir}/${program}${suffix} ${remotehost}:${remotedir}
done

programs=($(sed -n '5 p' config))
echo "Compiling background programs"
poly="${common} -DLOOPFOREVER"
suffix="_noise.elf"

for program in ${programs[*]}
do
	prog_size=$(scripts/computesize ${program} ${mem_size})
	size_flags="-DNI=${prog_size} -DNJ=${prog_size} -DNK=${prog_size} -DNL=${prog_size} -DNM=${prog_size} -DN=${prog_size} -DNX=${prog_size} -DNY=${prog_size}" 
	${compiler} ${poly} ${size_flags} ${srcdir}/${program}.c -o ${bindir}/${program}${suffix}
	if [ $? -ne 0 ]
	then
		echo "ERROR: Could not compile ${program}"
		rm crtbegin.o crtend.o
		exit 1
	fi
	scp ${bindir}/${program}${suffix} ${remotehost}:${remotedir}
done

rm crtbegin.o crtend.o
