#source scripts/analyze_auto/ips/tbtools.tcl
#source scripts/analyze_auto/ips/L2_tcdm_hybrid_interco.tcl
#source scripts/analyze_auto/ips/adv_dbg_if.tcl
#source scripts/analyze_auto/ips/apb2per.tcl
#source scripts/analyze_auto/ips/apb_adv_timer.tcl
#source scripts/analyze_auto/ips/apb_fll_if.tcl
#source scripts/analyze_auto/ips/apb_gpio.tcl
#source scripts/analyze_auto/ips/apb_node.tcl
#source scripts/analyze_auto/ips/apb_interrupt_cntrl.tcl
source scripts/analyze_auto/ips/axi.tcl
source scripts/analyze_auto/ips/axi_node.tcl
source scripts/analyze_auto/ips/axi_slice.tcl
source scripts/analyze_auto/ips/axi_slice_dc.tcl
source scripts/analyze_auto/ips/timer_unit.tcl
source scripts/analyze_auto/ips/common_cells.tcl
source scripts/analyze_auto/ips/fpnew.tcl
#source scripts/analyze_auto/ips/jtag_pulp.tcl
source scripts/analyze_auto/ips/riscv.tcl
#source scripts/analyze_auto/ips/ibex.tcl
source scripts/analyze_auto/ips/scm.tcl
source scripts/analyze_auto/ips/generic_FLL.tcl
source scripts/analyze_auto/ips/tech_cells_generic.tcl
#source scripts/analyze_auto/ips/udma_core.tcl
#source scripts/analyze_auto/ips/udma_uart.tcl
#source scripts/analyze_auto/ips/udma_i2c.tcl
#source scripts/analyze_auto/ips/udma_i2s.tcl
#source scripts/analyze_auto/ips/udma_qspi.tcl
#source scripts/analyze_auto/ips/udma_sdio.tcl
#source scripts/analyze_auto/ips/udma_camera.tcl
#source scripts/analyze_auto/ips/udma_filter.tcl
#source scripts/analyze_auto/ips/udma_external_per.tcl
source scripts/analyze_auto/ips/riscv-dbg.tcl
source scripts/analyze_auto/ips/axi2mem.tcl
source scripts/analyze_auto/ips/axi2per.tcl
source scripts/analyze_auto/ips/per2axi.tcl
source scripts/analyze_auto/ips/axi_size_conv.tcl
source scripts/analyze_auto/ips/cluster_interconnect.tcl
source scripts/analyze_auto/ips/event_unit_flex.tcl
source scripts/analyze_auto/ips/mchan.tcl
source scripts/analyze_auto/ips/hier-icache.tcl
source scripts/analyze_auto/ips/icache-intc.tcl
#source scripts/analyze_auto/ips/icache_mp_128_pf.tcl
#source scripts/analyze_auto/ips/icache_private.tcl
source scripts/analyze_auto/ips/cluster_peripherals.tcl
source scripts/analyze_auto/ips/fpu_div_sqrt_mvp.tcl
source scripts/analyze_auto/ips/fpu_interco.tcl
#source scripts/analyze_auto/ips/hwpe-ctrl.tcl
#source scripts/analyze_auto/ips/hwpe-stream.tcl
#source scripts/analyze_auto/ips/rbe.tcl
#source scripts/analyze_auto/ips/xne.tcl
source scripts/analyze_auto/ips/gf22_FLL.tcl
source scripts/analyze_auto/ips/tech_cells_GF22FDX.tcl
source scripts/analyze_auto/ips/marsellus_essentials.tcl
