#=====================================================
# Using vivado
#=====================================================

DESIGN 		= top
VCODE 		= vcode.f
WORK 		= worklib
TCL 		= tb_sim.tcl
DUMP 		= l1_dump
DUMP_VCD	= true

.DEFAULT: default
default : all

include ${COMMON_DIR}/common_makefile
