################################################################################
#
# snitch driver
#
################################################################################

SNITCH_DRIVER_VERSION = 0.1
SNITCH_DRIVER_SITE_METHOD = local
SNITCH_DRIVER_SITE = $(BR2_EXTERNAL_HERO_PATH)/support/snitch-driver
SNITCH_DRIVER_LICENSE = GPL
SNITCH_DRIVER_INSTALL_STAGING = YES
SNITCH_DRIVER_INSTALL_TARGET = NO

SNITCH_DRIVER_CFLAGS = -DDEBUG_LEVEL=$(BR2_PACKAGE_SNITCH_DRIVER_DEBUG_LEVEL)
ifneq ($(BR2_PACKAGE_SNITCH_DRIVER_DEBUG_LEVEL),0)
SNITCH_DRIVER_CFLAGS += -g
endif
SNITCH_DRIVER_CFLAGS += -DPLATFORM=$(BR2_PACKAGE_HERO_PLATFORM)

SNITCH_DRIVER_EXTERNAL_INC_PATHS = $(BR2_EXTERNAL_HERO_PATH)/support/include $(BR2_EXTERNAL_HERO_PATH)/support/snitch-driver

SNITCH_DRIVER_MK_OPTS = PLATFORM=$(BR2_PACKAGE_HERO_PLATFORM) CFLAGS="$(SNITCH_DRIVER_CFLAGS)"
SNITCH_DRIVER_MODULE_MAKE_OPTS = $(SNITCH_DRIVER_MK_OPTS)

SNITCH_DRIVER_TARGET_MAKE_ENV = $(TARGET_MAKE_ENV) $(SNITCH_DRIVER_MK_OPTS) \
	KERNEL_ARCH=$(KERNEL_ARCH) \
	KERNEL_DIR=$(LINUX_DIR) \
	KERNEL_CROSS_COMPILE=$(TARGET_CROSS) \
	CROSS_COMPILE=$(TARGET_CROSS) \
	INC_DIRS="$(SNITCH_DRIVER_EXTERNAL_INC_PATHS)"

define SNITCH_DRIVER_CLEAN_BUILD
	$(SNITCH_DRIVER_TARGET_MAKE_ENV) $(MAKE) -C $(@D) clean
endef
SNITCH_DRIVER_PRE_BUILD_HOOKS += SNITCH_DRIVER_CLEAN_BUILD

define SNITCH_DRIVER_BUILD_CMDS
	$(SNITCH_DRIVER_TARGET_MAKE_ENV) $(MAKE) -C $(@D) build
endef

define SNITCH_DRIVER_INSTALL_STAGING_CMDS
	$(INSTALL) -D -m 0644 $(@D)/snitch_module.h $(STAGING_DIR)/usr/include/snitch_module.h
endef

define SNITCH_DRIVER_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0644 $(@D)/snitch.ko $(TARGET_DIR)/lib/modules/$(LINUX_VERSION_PROBED)/extra/snitch.ko
endef

$(eval $(generic-package))
