#!/usr/bin/env bash
#
# Copyright (c) 2020 ETH Zurich, University of Bologna
# Licensed under the Apache License, Version 2.0.
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
# - Andreas Kurth <akurth@iis.ee.ethz.ch>

set -euo pipefail
readonly THIS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

"$THIS_DIR/libpulp"
"$THIS_DIR/pulp-driver"
"$THIS_DIR/hero-openmp"
"$THIS_DIR/libhero-target"
"$THIS_DIR/prem-cmux"
