#!/usr/bin/env bash

set -eo pipefail

export HERCULES_INSTALL=${HERO_INSTALL}
export HERCULES_ARCH="PULP"
export HERCULES_FORCE_FOOTPRINT_DENSE=1
export HERCULES_CPU_MEMORY_SIZE=32768
export HERCULES_DISQ_THRESHOLD=0
export HERCULES_DEFAULT_NUM_THREADS=8
export HERCULES_DMA_ENFORCE
export HERCULES_NO_INTERVAL_CONTROLFLOW
export HERCULES_WHITELIST="gemm_nn gemm_cpu gemm
forward_convolutional_layer forward_network network_predict network_predict_image main
.omp_outlined.
.omp_outlined..1
.omp_outlined..2
.omp_outlined..3
.omp_outlined..4
.omp_outlined..5
.omp_outlined..6
.omp_outlined..7
.omp_outlined..8
.omp_outlined..9
.omp_outlined..10
.omp_outlined..11
.omp_outlined..12
.omp_outlined..13
"
source ${HERCULES_INSTALL}/../toolchain/HerculesCompiler-public/environment.sh

source ${HERO_INSTALL}/../env/exilzcu102.sh
make default-as=pulp clean all
