#!/bin/bash
set -o errexit
export HERO_INSTALL=/scratch/mmaxim/hero/install
export HERCULES_INSTALL=${HERO_INSTALL}
export HERCULES_ARCH="PULP"
export CMUX_ROOT="/scratch/mmaxim/cmux"
export HERCULES_FORCE_FOOTPRINT_DENSE=1
export HERCULES_CPU_MEMORY_SIZE=32768
export HERCULES_DISQ_THRESHOLD=0
export HERCULES_DEFAULT_NUM_THREADS=8
export HERCULES_DMA_ENFORCE
export HERCULES_NO_INTERVAL_CONTROLFLOW
export HERCULES_WHITELIST="gemm_nn gemm_cpu gemm
forward_convolutional_layer forward_network network_predict network_predict_image main
gemm_0
gemm_2
gemm_4
gemm_6
gemm_8
gemm_10
gemm_12
gemm_13
gemm_14
gemm_15
gemm_18
gemm_21
gemm_22
.omp_outlined.
.omp_outlined..1
.omp_outlined..2
.omp_outlined..3
.omp_outlined..4
.omp_outlined..5
.omp_outlined..6
.omp_outlined..7
.omp_outlined..8
.omp_outlined..9
.omp_outlined..10
.omp_outlined..11
.omp_outlined..12
.omp_outlined..13
"
source ${HERCULES_INSTALL}/../toolchain/HerculesCompiler-public/environment.sh

source ${HERO_INSTALL}/../env/exilzcu102.sh
make default-as=pulp clean all
scp darknet root@hero-zcu102-06:/home/root/mmaxim/
