void gemm_0(float ALPHA, float *A, float *B, float *C);
void gemm_2(float ALPHA, float *A, float *B, float *C);
void gemm_4(float ALPHA, float *A, float *B, float *C);
void gemm_6(float ALPHA, float *A, float *B, float *C);
void gemm_8(float ALPHA, float *A, float *B, float *C);
void gemm_10(float ALPHA, float *A, float *B, float *C);
void gemm_12(float ALPHA, float *A, float *B, float *C);
void gemm_13(float ALPHA, float *A, float *B, float *C);
void gemm_14(float ALPHA, float *A, float *B, float *C);
void gemm_15(float ALPHA, float *A, float *B, float *C);
void gemm_18(float ALPHA, float *A, float *B, float *C);
void gemm_21(float ALPHA, float *A, float *B, float *C);
void gemm_22(float ALPHA, float *A, float *B, float *C);
void gemm_nn_manual_DMA(int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float *C, int ldc);
void gemm_nn_tiled(int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float *C, int ldc);
