
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[106]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[126]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awsize[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[47]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[7]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[6]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[9]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[77]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[80]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[37]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[48]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[19]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[74]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[87]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[103]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[106]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[38]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[29]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[30]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[63]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[60]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[20]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[116]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[112]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[122]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[125]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awsize[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[9]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[14]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[79]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[26]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[47]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[54]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[73]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[28]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[18]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[105]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[110]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[48]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[37]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[29]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[38]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[59]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rresp[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[19]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[84]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[102]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[11]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[99]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_bresp[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[13]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[46]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[6]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[14]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[25]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[36]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[53]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[70]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[17]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[86]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[27]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[102]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[109]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[118]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[47]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[28]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[24]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[58]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[37]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[83]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[115]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[123]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[124]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[45]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awqos[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[13]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[16]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[35]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[46]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[69]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[85]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[60]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[101]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[117]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[58]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[23]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[27]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[36]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[28]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[57]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[10]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[50]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[114]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[107]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awburst[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awprot[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[17]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[22]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[31]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[40]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[55]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[90]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[120]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[33]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[75]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[7]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[17]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[68]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[41]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[18]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arburst[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[48]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[117]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[108]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[100]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[21]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[7]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awburst[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[39]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[64]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[24]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[76]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[89]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[119]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[40]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[67]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arsize[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[17]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[32]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[66]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[47]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[70]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[88]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[111]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[126]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[8]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[12]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[23]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awsize[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[10]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[66]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[63]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[75]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[82]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[96]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[112]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[16]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[39]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[16]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[65]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[31]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[40]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[72]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[69]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[87]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[113]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[101]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[78]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[48]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[8]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[15]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[38]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[20]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[81]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[88]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[95]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[104]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[111]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[65]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[7]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[30]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[15]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[71]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[64]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[39]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[110]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[6]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[10]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[13]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[29]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[27]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[51]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[6]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[20]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[34]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[62]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[98]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[114]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[107]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[79]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[94]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[49]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[11]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arqos[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[22]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[43]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arprot[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[44]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[33]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[20]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[91]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arcache[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[9]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[11]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[109]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[24]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[33]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awcache[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awprot[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[42]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[72]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[97]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[56]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[38]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[93]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[122]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[113]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[61]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[19]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arqos[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[21]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[32]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[43]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[22]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[19]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[90]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[62]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arcache[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[118]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[120]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[9]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[14]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[23]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awprot[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awcache[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[78]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[37]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[92]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[55]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[44]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[121]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[71]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[41]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[86]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[10]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[31]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[42]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[61]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[21]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[89]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[6]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[98]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[125]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[97]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[127]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[18]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[32]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[85]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[56]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[77]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[91]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[34]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[76]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[43]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[8]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[41]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[18]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[6]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[16]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[42]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arprot[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arburst[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[124]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[127]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[7]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[15]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[105]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_bresp[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awqos[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[15]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[52]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[30]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[40]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[59]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[94]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[123]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[36]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[57]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[45]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arqos[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[35]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[46]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[36]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[27]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[14]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[8]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[46]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[49]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[103]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[22]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[29]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[54]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[51]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[74]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[12]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[68]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[39]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[84]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[93]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[100]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[35]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[116]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arqos[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arcache[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[45]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[26]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[82]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arsize[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[32]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[35]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[24]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[13]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[45]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[121]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[104]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[11]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[44]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awcache[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awqos[1]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[53]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[26]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[67]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rresp[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[115]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[99]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[42]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[83]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[21]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[73]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[25]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[81]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[34]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[23]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[26]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[31]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arsize[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arcache[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[96]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[119]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[30]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[28]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awcache[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awqos[0]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[52]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[25]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[50]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[80]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[41]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[108]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[5]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[43]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[12]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arprot[2]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[44]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[4]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[33]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[92]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[34]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[25]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[12]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[7]}]
set_property MARK_DEBUG true [get_nets {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[95]}]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_aruser]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_arlock]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_arready]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_arvalid]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_awlock]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_awready]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_awuser]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_awvalid]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_bready]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_rvalid]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_wready]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_wvalid]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_wlast]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_bvalid]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_rlast]
set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_zynq_ps/saxigp3_rready]

set_property MARK_DEBUG true [get_nets hero_exilzcu102_i/i_pulp/inst/mbox_irq_o]
connect_debug_port u_ila_0/probe28 [get_nets [list hero_exilzcu102_i/i_pulp/inst/rab_from_host_miss_irq_o]]
connect_debug_port u_ila_0/probe29 [get_nets [list hero_exilzcu102_i/i_pulp/inst/rab_from_host_multi_irq_o]]
connect_debug_port u_ila_0/probe30 [get_nets [list hero_exilzcu102_i/i_pulp/inst/rab_from_host_prot_irq_o]]
connect_debug_port u_ila_0/probe31 [get_nets [list hero_exilzcu102_i/i_pulp/inst/rab_from_pulp_miss_irq_o]]
connect_debug_port u_ila_0/probe32 [get_nets [list hero_exilzcu102_i/i_pulp/inst/rab_from_pulp_multi_irq_o]]
connect_debug_port u_ila_0/probe33 [get_nets [list hero_exilzcu102_i/i_pulp/inst/rab_from_pulp_prot_irq_o]]
connect_debug_port u_ila_0/probe34 [get_nets [list hero_exilzcu102_i/i_pulp/inst/rab_miss_fifo_full_irq_o]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list hero_exilzcu102_i/i_zynq_ps/inst/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[5]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[6]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arlen[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_arprot[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arprot[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arprot[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_awprot[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awprot[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awprot[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_bresp[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_bresp[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 6 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rid[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[5]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[6]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awlen[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 3 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_awsize[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awsize[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awsize[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 49 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[5]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[6]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[7]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[8]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[9]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[10]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[11]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[12]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[13]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[14]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[15]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[16]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[17]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[18]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[19]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[20]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[21]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[22]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[23]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[24]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[25]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[26]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[27]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[28]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[29]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[30]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[31]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[32]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[33]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[34]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[35]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[36]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[37]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[38]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[39]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[40]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[41]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[42]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[43]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[44]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[45]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[46]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[47]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_araddr[48]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 4 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_arqos[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arqos[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arqos[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arqos[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 3 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_arsize[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arsize[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arsize[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 2 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_rresp[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rresp[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 6 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_bid[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 2 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_awburst[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awburst[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 128 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[5]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[6]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[7]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[8]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[9]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[10]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[11]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[12]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[13]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[14]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[15]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[16]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[17]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[18]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[19]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[20]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[21]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[22]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[23]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[24]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[25]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[26]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[27]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[28]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[29]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[30]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[31]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[32]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[33]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[34]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[35]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[36]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[37]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[38]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[39]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[40]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[41]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[42]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[43]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[44]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[45]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[46]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[47]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[48]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[49]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[50]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[51]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[52]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[53]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[54]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[55]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[56]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[57]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[58]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[59]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[60]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[61]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[62]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[63]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[64]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[65]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[66]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[67]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[68]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[69]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[70]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[71]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[72]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[73]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[74]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[75]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[76]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[77]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[78]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[79]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[80]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[81]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[82]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[83]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[84]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[85]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[86]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[87]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[88]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[89]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[90]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[91]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[92]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[93]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[94]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[95]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[96]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[97]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[98]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[99]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[100]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[101]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[102]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[103]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[104]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[105]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[106]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[107]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[108]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[109]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[110]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[111]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[112]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[113]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[114]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[115]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[116]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[117]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[118]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[119]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[120]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[121]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[122]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[123]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[124]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[125]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[126]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_rdata[127]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 6 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awid[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 6 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arid[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 4 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_awqos[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awqos[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awqos[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awqos[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 2 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_arburst[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arburst[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 4 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_arcache[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arcache[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arcache[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_arcache[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 49 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[5]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[6]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[7]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[8]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[9]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[10]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[11]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[12]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[13]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[14]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[15]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[16]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[17]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[18]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[19]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[20]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[21]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[22]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[23]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[24]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[25]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[26]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[27]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[28]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[29]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[30]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[31]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[32]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[33]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[34]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[35]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[36]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[37]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[38]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[39]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[40]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[41]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[42]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[43]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[44]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[45]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[46]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[47]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awaddr[48]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 4 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_awcache[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awcache[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awcache[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_awcache[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 16 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[5]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[6]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[7]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[8]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[9]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[10]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[11]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[12]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[13]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[14]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wstrb[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 128 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[0]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[1]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[2]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[3]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[4]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[5]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[6]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[7]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[8]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[9]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[10]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[11]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[12]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[13]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[14]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[15]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[16]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[17]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[18]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[19]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[20]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[21]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[22]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[23]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[24]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[25]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[26]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[27]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[28]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[29]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[30]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[31]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[32]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[33]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[34]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[35]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[36]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[37]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[38]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[39]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[40]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[41]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[42]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[43]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[44]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[45]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[46]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[47]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[48]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[49]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[50]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[51]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[52]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[53]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[54]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[55]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[56]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[57]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[58]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[59]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[60]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[61]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[62]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[63]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[64]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[65]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[66]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[67]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[68]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[69]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[70]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[71]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[72]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[73]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[74]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[75]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[76]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[77]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[78]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[79]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[80]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[81]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[82]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[83]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[84]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[85]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[86]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[87]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[88]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[89]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[90]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[91]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[92]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[93]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[94]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[95]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[96]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[97]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[98]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[99]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[100]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[101]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[102]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[103]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[104]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[105]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[106]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[107]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[108]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[109]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[110]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[111]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[112]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[113]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[114]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[115]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[116]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[117]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[118]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[119]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[120]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[121]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[122]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[123]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[124]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[125]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[126]} {hero_exilzcu102_i/i_zynq_ps/saxigp3_wdata[127]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {hero_exilzcu102_i/i_pulp/inst/i_bound/i_bound/gen_clusters[0].gen_cluster_sync.i_cluster/cl_busy_o}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list hero_exilzcu102_i/i_pulp/inst/cl_busy_o]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {hero_exilzcu102_i/i_pulp/inst/i_bound/i_bound/gen_clusters[0].gen_cluster_sync.i_cluster/cl_eoc_o}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list hero_exilzcu102_i/i_pulp/inst/cl_eoc_o]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list hero_exilzcu102_i/i_pulp/inst/mbox_irq_o]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_arlock]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_aruser]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_awlock]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_awuser]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_bready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_bvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_rlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_wlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list hero_exilzcu102_i/i_zynq_ps/saxigp3_wvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_pl_clk0]
