#!/bin/bash -ex

install_dir=$TARGET_INSTALL_DIR
ws_install_dir=$INSTALL_DIR
build_dir=$BUILD_DIR

if [ -z "$install_dir" ]; then
  install_dir=$PWD/install
fi

if [ -z "$ws_install_dir" ]; then
  ws_install_dir=$PWD/install/ws
fi

if [ -z "$build_dir" ]; then
  build_dir=$PWD/build
fi

export PATH=$ws_install_dir/bin:$PATH
export PYTHONPATH=$ws_install_dir/python:$PYTHONPATH
export PULP_CONFIGS_PATH=$ws_install_dir/configs

make -C json-tools all install BUILD_DIR=$build_dir/json-tools INSTALL_DIR=$ws_install_dir

make -C pulp-configs all_scons BUILD_DIR=$build_dir/pulp-configs INSTALL_DIR=$ws_install_dir TARGET_INSTALL_DIR=$install_dir

make -C runner sdk.build BUILD_DIR=$build_dir/gvsoc INSTALL_DIR=$ws_install_dir TARGET_INSTALL_DIR=$install_dir

make -C plptest build BUILD_DIR=$build_dir/gvsoc INSTALL_DIR=$ws_install_dir TARGET_INSTALL_DIR=$install_dir

make -C pulp-debug-bridge all BUILD_DIR=$build_dir/pulp-debug-bridge INSTALL_DIR=$ws_install_dir TARGET_INSTALL_DIR=$install_dir

make -C dpi-models build install BUILD_DIR=$build_dir/archi INSTALL_DIR=$ws_install_dir TARGET_INSTALL_DIR=$install_dir
