#!/bin/sh

# ======================== CONFIGURATION OPTIONS =========================== #

# HERCULES passes build directory.
PASSROOT="$HERO_INSTALL/lib/llvm-support"

# LLVM bin directory (empty for standard PATH).
# Note: Must end with slash character ("/") unless empty.
LLVM_BIN_DIR="$HERO_INSTALL/bin/"

# Additional compilation flag for the final step (IR -> bin)
CFLAGS=""

# ============================= SANITY CHECK =============================== #

BASENAME=$(basename "$1" .ll)

# Ensure that a file name was given as argument.
if [ -z "$1" ]; then
  echo "Fatal error: Provide IR file as arg 1!"
  exit 1
fi

if [ -z "$2" ]; then
  echo "Fatal error: Provide pass library name as arg 2!"
  exit 1
fi

if [ -z "$3" ]; then
  echo "Fatal error: Provide pass name as arg 3!"
  exit 1
fi

OUTPUT=$BASENAME.OMP.ll
if [ ! -z "$4" ]; then
  OUTPUT=$4
fi

# ========================= EXECUTION PARAMETERS =========================== #

# Path to the passes, based on provided root directory.
PASS_OMP_PATH="$PASSROOT/lib$2.so"

# LLVM pass names.
PASS_OMP_NAME="-$3"

# Extra arguments
EXTRA_ARGS="$5"

# Passes to run before each HERCULES pass.
PASS_OMP_PREREQ=""

# Passes to run at the very end.
FINAL_OPTIMIZATIONS="-dce -gvn -instcombine -mergefunc -always-inline -simplifycfg -instcombine -elim-avail-extern -branch-prob -loop-unroll -globaldce -constmerge -always-inline"

# =============================== EXECUTION ================================ #

${LLVM_BIN_DIR}opt "$BASENAME.ll" \
-load="$PASS_OMP_PATH" $EXTRA_ARGS $PASS_OMP_PREREQ $PASS_OMP_NAME \
$FINAL_OPTIMIZATIONS -o "$OUTPUT" -S

# Check that the passes were successful before continuing.
if [ $? -ne 0 ]; then
  echo "Application of passes to $BASENAME failed, stopping here."
  exit 1
fi
